### ISSUE TITLE
TODO for release 1.0

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/demo_geluidmodel#1]
Prio1:
- [x] Fix breaklines (follow bridge, more lines visible)
- [ ] Add hard-zacht areas
- [ ] Fix bridge
- [x] Prepare downloads
- [x] Add 'maaiveldhoogte' to buildings
- [x] Finish LOD2 buildings
- [x] Finish LOD1+ buildings
- [x] Finish LOD1 buildings

Prio2:
- [x] Turntable navigation
- [x] Improve performance (simplify LOD2 buildings)
- [ ] Add noisecontours
- [ ] Add edgelines to buildings
- [ ] Add extra information to buildings (functie, bouwjaar, ahn vliegjaar, adressen)

Prio 3:
- [x] Clean area from excess terrain
- [ ] Add noise
- [ ] Display extra building information on mouseover
